### ISSUE TITLE
Suspected incorrect usage of uctypes offset

### ISSUE THREAD

**Issue by pfalcon** [dmazzella/uble#4]
https://github.com/dmazzella/uble/blob/60ad4f06c2c4d1b732a2fc4ab566760f93d09e92/bluetooth_low_energy/protocols/hci/__init__.py#L30 this defines a structure where UINT16 "opcode" field as at offset 0, then UINT8 "length" field is at offset 1, i.e. overlaps "opcode" field.

There're similar cases below that line too. Are these structure definitions actually used/tested?

**Comment by dmazzella** [comment]
No one of the structures defined in uble/bluetooth_low_energy/protocols/hci/__init__.py are used.
Now fixed, thanks for the segnalation.
