### ISSUE TITLE
Can this library support nucleo l476rg 

### ISSUE THREAD

**Issue by MatenatK** [dmazzella/uble#5]
firstly, I wanna tell you that this is an awesome library. But this library can support another Micropython board, for example, Nucleo L476rg? or support Stm32F405 only?

**Comment by dmazzella** [comment]
Thank you for using it! This library has been designed to make it easier to use on different MCU's. Have you tried using it and had problems? I do not have the nucleo and I can not test it. If it doesnt work write in this issue and i check it!

**Comment by MatenatK** [comment]
I have tried to use the library basic.py with Nucleo L476RG but it did not work, Putty showed that "Error reading from serial device", by the way, it works on Pyboard

![image](https://user-images.githubusercontent.com/40523961/41842177-46b8071c-7894-11e8-8ceb-69d0be052409.png)

**Comment by dmazzella** [comment]
Have you tried to change the nss pin (in your configuration A4) with the A1 pin?

`nss_pin=machine.Pin('A4', machine.Pin.OUT_PP),`
`nss_pin=machine.Pin('A1', machine.Pin.OUT_PP),`

**Comment by MatenatK** [comment]
Yeah, I have tried to change the nss pin but it still doesn't work

![ble2](https://user-images.githubusercontent.com/40523961/41850713-cb4a3156-78af-11e8-9f28-252bc3e398a7.jpg)

**Comment by dmazzella** [comment]
Can you share a photo of phisical connection?

**Comment by MatenatK** [comment]
Yeah this is my physical connection
![ble2](https://user-images.githubusercontent.com/40523961/41853964-4217f9cc-78b9-11e8-81f0-143825583e0b.jpg)

**Comment by dmazzella** [comment]
Try to remap the SPI1 Pins

```
// SPI busses
#define MICROPY_HW_SPI1_NSS     (pin_A4)
#define MICROPY_HW_SPI1_SCK     (pin_B3)
#define MICROPY_HW_SPI1_MISO    (pin_B4)
#define MICROPY_HW_SPI1_MOSI    (pin_B5)
```

```
// SPI busses
#define MICROPY_HW_SPI1_NSS     (pin_A4)
#define MICROPY_HW_SPI1_SCK     (pin_A5)
#define MICROPY_HW_SPI1_MISO    (pin_A6)
#define MICROPY_HW_SPI1_MOSI    (pin_A7)
```

**Comment by MatenatK** [comment]
I have remapped but still doesn't work

![ble3](https://user-images.githubusercontent.com/40523961/41859153-bcef6eee-78c5-11e8-8560-3b6973cdd223.jpg)

**Comment by dmazzella** [comment]
Have you tried to set pins (reset and nss) high and low manually for see if any of this cause the REPL conflict?

A1 and B9

```
import machine
_pin=machine.Pin('A1', machine.Pin.OUT_PP)
_pin.on()
_pin.off()
```

**Comment by MatenatK** [comment]
A1 B8 B9 are working

![ble4](https://user-images.githubusercontent.com/40523961/41860599-3cbbb1b6-78c9-11e8-9ade-6d192a429187.jpg)

**Comment by MatenatK** [comment]
I have tried to run basic.py without connection with IDB05A1 board on both Pyboard and Nucleo L476RG, the result shows below.

![ble4](https://user-images.githubusercontent.com/40523961/41863133-1045afd6-78d0-11e8-8e88-15e8eed5e56a.jpg)

I think maybe L476RG is not suitable for this library because when I tried to run basic.py Putty would be an error.

**Comment by dmazzella** [comment]
As soon as possible i buy a Nucleo L476RG to test it.
Without the board i can't see exactly the problem.

**Comment by MatenatK** [comment]
Oh thank you, tomorrow I will test the library with other board: F767ZI F401 F411 F407

thank you for your help

**Comment by dmazzella** [comment]
Excuse me, can you send me the ports\stm32\boards\NUCLEO_L476RG folder and the stm32l476_af.csv file?

I would like to verify the configuration you are using.

Why do you use the version of MicroPython 1.9.3? some particular needs? 
uble is the latest from repository?

How is the board connected to the REPL?

**Comment by MatenatK** [comment]
OMG! I have changed a Micropython version to 1.9.4 and then! the library works!, By the way, can this library connect to other IDB05A1 board and send some data?

![ble4](https://user-images.githubusercontent.com/40523961/41884732-d563eb72-791e-11e8-9ff5-6a0bb1b55eab.jpg)

**Comment by dmazzella** [comment]
> can this library connect to other IDB05A1 board and send some data?

Yes it can, for more info you can refer to [BlueNRG, BlueNRG-MS stacks programming guidelines](http://www.st.com/resource/en/programming_manual/dm00141271.pdf) and examples from [STSW-BLUENRG-DK 2.0.2](http://www.st.com/en/embedded-software/stsw-bluenrg-dk.html).

I close this issue as soved.

In case of problems regards examples and demo software open a more specific issue.
